from django.contrib import admin
from django.urls import path,include
from MyApp import views as App_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('MyApp/',include('MyApp.urls')),
    path('login/',App_views.login),
    path('register/',App_views.register),
    path('manager_login/',App_views.manager_login),
    path('doctor_login/',App_views.doctor_login),
    path('resident_login/',App_views.resident_login),
    path('resident_register/',App_views.resident_register),
    path('doctor_register/',App_views.doctor_register),
    path('back1/',App_views.back1),
    path('back2/',App_views.back2),

    path('personal_info/',App_views.personal_info),
    path('calculate_BMI/',App_views.calculate_BMI),
    path('health_reports/',App_views.health_reports),
    path('search_family/',App_views.search_family),
    path('add_family/',App_views.add_family),
    path('search_doctor/',App_views.search_doctor),
    path('appoint_doctor/',App_views.appoint_doctor),
    path('new_message/',App_views.new_message),
    path('alter_password/',App_views.alter_password),
    path('home_page/',App_views.home_page),
    path('delete_report/',App_views.delete_report),
    path('delete_family_report',App_views.delete_family_report),
    path('family_calculate/',App_views.family_calculate),
    path('delete_family/',App_views.delete_family),
    path('alter_family/',App_views.alter_family),
    path('delete_appoint/',App_views.delete_appoint),
    path('doctor_info/',App_views.doctor_info),
    path('consult_doctor/',App_views.consult_doctor),
    path('search_d/',App_views.search_d),
    path('search_teams/',App_views.search_teams),
    path('resident_receive_message/',App_views.resident_receive_message),
    path('resident_delete_message/',App_views.resident_delete_message),
    path('cancel_appoint/',App_views.cancel_appoint),

    path('alter_doctor_password/',App_views.alter_doctor_password),
    path('appoint_resident/',App_views.appoint_resident),
    path('appoint_service_team/',App_views.appoint_service_team),
    path('doctor_home_page/',App_views.doctor_home_page),
    path('doctor_personal_info/',App_views.doctor_personal_info),
    path('doctor_new_message/',App_views.doctor_new_message),
    path('search_service_team/',App_views.search_service_team),
    path('doctor_appoint_message/',App_views.doctor_appoint_message),
    path('doctor_receive_message/',App_views.doctor_receive_message),
    path('appoint_detail/',App_views.appoint_detail),
    path('doctor_delete_message/',App_views.doctor_delete_message),
    path('delete_teams/',App_views.delete_teams),
    path('contact_resident/',App_views.contact_resident),
    path('delete_appoint/',App_views.delete_appoint),
    path('resident_info/',App_views.resident_info),
    path('resident_health_report/',App_views.resident_health_report),
    path('resident_family/',App_views.resident_family),
    path('resident_family_health_report/',App_views.resident_family_health_report),

    path('alter_manager_password/',App_views.alter_manager_password),
    path('search_resident/',App_views.search_resident),
    path('search_doctors/',App_views.search_doctors),
    path('search_team/',App_views.search_team),
    path('search_account/',App_views.search_account),
    path('manager_home_page/',App_views.manager_home_page),
    path('delete_account/',App_views.delete_account),
    path('delete_resident/',App_views.delete_resident),
    path('delete_doctor/',App_views.delete_doctor),
    path('delete_team/',App_views.delete_team),
    path('manager_search_message/',App_views.manager_search_message),
    path('manager_search_appoint/',App_views.manager_search_appoint),
    path('manager_search_a/',App_views.manager_search_a),
    path('manager_delete_appoint/',App_views.manager_delete_appoint),
    path('manager_delete_message/',App_views.manager_delete_message),
]
