# Generated by Django 2.0 on 2019-05-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_telephone', models.CharField(max_length=20)),
                ('doctor_telephone', models.CharField(max_length=20)),
                ('resident_appoint_time', models.CharField(max_length=20)),
                ('resident_request_time', models.CharField(max_length=20)),
                ('IsRead', models.CharField(max_length=20, null=True)),
                ('doctor_deal_time', models.CharField(max_length=20, null=True)),
                ('appoint_result', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=20)),
                ('doctor_sex', models.CharField(max_length=20)),
                ('doctor_age', models.CharField(max_length=20)),
                ('doctor_telephone', models.CharField(max_length=20)),
                ('doctor_work_time', models.CharField(max_length=50)),
                ('doctor_level', models.CharField(max_length=50)),
                ('doctor_dept', models.CharField(max_length=50)),
                ('doctor_condition', models.CharField(max_length=50, null=True)),
                ('doctor_hospital', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=20)),
                ('family_sex', models.CharField(max_length=10)),
                ('family_age', models.CharField(max_length=10)),
                ('family_relationship', models.CharField(max_length=10)),
                ('family_telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Health_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=20)),
                ('report_telephone', models.CharField(max_length=20)),
                ('report_height', models.CharField(max_length=20)),
                ('report_weight', models.CharField(max_length=20)),
                ('result_num', models.CharField(max_length=20)),
                ('result_condition', models.CharField(max_length=20)),
                ('report_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_send', models.CharField(max_length=20)),
                ('message_receive', models.CharField(max_length=20)),
                ('send_time', models.CharField(max_length=20, null=True)),
                ('is_read', models.CharField(max_length=20, null=True)),
                ('information', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_name', models.CharField(max_length=20)),
                ('resident_sex', models.CharField(max_length=10)),
                ('resident_age', models.CharField(max_length=10)),
                ('resident_telephone', models.CharField(max_length=20)),
                ('resident_address', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30)),
                ('team_telephone', models.CharField(max_length=20)),
                ('team_introduction', models.CharField(max_length=50, null=True)),
                ('team_condition', models.CharField(max_length=20)),
                ('team_appoint_doctor', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_telephone', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=20)),
                ('user_identity', models.CharField(max_length=20)),
            ],
        ),
    ]
