# Generated by Django 2.1.4 on 2019-05-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_auto_20190527_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='resident_condition',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
