# Generated by Django 2.1.4 on 2019-05-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_auto_20190528_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appoint',
            options={'ordering': ['resident_telephone']},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['doctor_telephone']},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['family_telephone']},
        ),
        migrations.AlterModelOptions(
            name='health_report',
            options={'ordering': ['report_telephone']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['message_send']},
        ),
        migrations.AlterModelOptions(
            name='resident',
            options={'ordering': ['resident_telephone']},
        ),
        migrations.AlterModelOptions(
            name='service_team',
            options={'ordering': ['team_name']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['user_telephone']},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=20),
        ),
        migrations.AlterField(
            model_name='resident',
            name='resident_sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=10),
        ),
    ]
