# Generated by Django 2.1.4 on 2019-05-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_auto_20190528_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=20),
        ),
    ]
